"""Capability statuses, generated.

Generated by tools/sync-status.mjs from api-spec/status.json. Do not edit by hand —
run `node tools/sync-status.mjs` instead. CI fails if this drifts.

Exposed so an application can render honest state without hard-coding a copy that
quietly goes stale — the failure this whole file exists to prevent.
"""

from __future__ import annotations

from types import MappingProxyType

__all__ = [
    "VERIFIED_AT",
    "CAPABILITIES",
    "AREA_BASE_URLS",
    "AREAS",
    "capability_status",
    "find_capability",
    "is_implemented",
]

#: When the matrix was last verified against the live network.
VERIFIED_AT = "2026-08-14"

#: Every capability, nested by area.
#:
#: Nested rather than flat because ``GET /health`` exists on both the registry
#: and the demo node. They are different endpoints on different hosts, and
#: flattening them into one key silently lost one of the two.
CAPABILITIES = MappingProxyType({
    "discovery": MappingProxyType({
        "GET /health": "implemented",
        "GET /nodes": "implemented",
        "GET /peers": "implemented",
        "GET /api/v1/peers": "not_yet_wired",
        "POST /api/v1/register": "implemented",
        "POST /api/v1/heartbeat": "implemented",
        "GET /nodes?callable=1": "implemented",
    }),
    "binding": MappingProxyType({
        "POST /v1/bindings/initiate": "implemented",
        "POST /v1/bindings/resolve": "implemented",
        "POST /v1/bindings/authorize": "implemented",
        "GET /v1/bindings/{binding_session_id}/status": "implemented",
        "POST /v1/bindings/{binding_session_id}/cancel": "implemented",
        "POST /v1/node/bindings/pending": "implemented",
        "POST /v1/node/bindings/{binding_session_id}/accept": "implemented",
        "POST /v1/node/bindings/{binding_session_id}/reject": "implemented",
    }),
    "identity": MappingProxyType({
        "POST /v1/auth/challenge": "implemented",
        "POST /v1/auth/device-login": "implemented",
        "GET /v1/operator/me/nodes": "implemented",
    }),
    "coordination": MappingProxyType({
        "GET /healthz": "implemented",
        "GET /version": "implemented",
        "GET /openapi.json": "implemented",
        "GET /v1/capabilities": "implemented",
        "POST /v1/intents": "implemented",
        "GET /v1/sessions/{session_id}": "implemented",
        "GET /v1/sessions/{session_id}/proposal": "implemented",
        "POST /v1/sessions/{session_id}/commitment": "implemented",
        "GET /v1/sessions/{session_id}/commitment": "implemented",
        "POST /v1/sessions/{session_id}/authorize": "implemented",
        "POST /v1/sessions/{session_id}/cancel": "implemented",
        "GET /v1/sessions/{session_id}/result": "implemented",
        "GET /v1/sessions/{session_id}/receipt": "implemented",
        "GET /v1/sessions/{session_id}/events": "implemented",
        "POST /v1/objects": "implemented",
        "GET /v1/objects/{object_id}": "implemented",
        "POST /v1/runtimes": "implemented",
    }),
    "compute": MappingProxyType({
        "GET /": "implemented",
        "GET /healthz": "implemented",
        "GET /readyz": "implemented",
        "GET /version": "implemented",
        "GET /openapi.json": "implemented",
        "GET /v1/task-package": "implemented",
        "POST /v1/derive-core-intent": "implemented",
        "POST /v1/intents": "implemented",
        "GET /v1/sessions/{session_id}": "implemented",
        "GET /v1/sessions/{session_id}/proposal": "implemented",
        "POST /v1/sessions/{session_id}/commitment": "implemented",
        "POST /v1/sessions/{session_id}/authorize": "implemented",
        "POST /v1/sessions/{session_id}/cancel": "implemented",
        "GET /v1/sessions/{session_id}/result": "implemented",
        "GET /v1/sessions/{session_id}/receipt": "implemented",
        "GET /v1/sessions/{session_id}/events": "implemented",
        "POST /v1/objects": "implemented",
        "POST /v1/runtimes": "implemented",
    }),
    "economics": MappingProxyType({
        "GET /v1/operator/me/credits": "not_yet_wired",
        "GET /v1/operator/me/evidence": "not_yet_wired",
    }),
    "oracle": MappingProxyType({
        "CONTRACT EvidenceOracle.submitEvidence": "testing",
        "CONTRACT PythPriceAdapter.getPrice": "testing",
        "GET /v1/oracle/price": "planned",
        "POST /v1/oracle/report": "planned",
    }),
    "wallet": MappingProxyType({
        "POST /v1/wallet/create": "planned",
        "POST /v1/wallet/session-key": "planned",
        "POST /v1/wallet/transfer": "planned",
    }),
    "dex": MappingProxyType({
        "POST /v1/dex/intent": "planned",
        "GET /v1/dex/quote": "planned",
        "POST /v1/dex/solve": "planned",
        "GET /v1/dex/pools": "planned",
    }),
    "demo": MappingProxyType({
        "GET /health": "implemented",
        "GET /identity": "implemented",
        "POST /echo": "implemented",
        "GET /verify-instructions": "implemented",
    }),
    "community": MappingProxyType({
        "LINK https://discord.gg/libertynet": "planned",
        "LINK https://github.com/LibertyNetHQ": "implemented",
    }),
})

#: Base URL per area. ``None`` where the area is not an HTTP surface.
AREA_BASE_URLS = MappingProxyType({
    "discovery": "https://registry.libertynet.ai",
    "binding": "https://registry.libertynet.ai",
    "identity": "https://registry.libertynet.ai",
    "coordination": "https://libertynet.ai/coordination",
    "compute": "https://libertynet.ai/compute",
    "economics": "https://registry.libertynet.ai",
    "oracle": None,
    "wallet": None,
    "dex": None,
    "demo": "https://libertynet.ai/demo-node",
    "community": None,
})

#: Areas, in the order the matrix lists them.
AREAS = ("discovery", "binding", "identity", "coordination", "compute", "economics", "oracle", "wallet", "dex", "demo", "community")


def capability_status(area: str, method: str, path: str) -> str | None:
    """Status of one capability within an area, or ``None`` if not listed."""
    return CAPABILITIES.get(area, {}).get(f"{method} {path}")


def find_capability(method: str, path: str) -> list[tuple[str, str]]:
    """Find a capability without knowing its area.

    Returns every match, because more than one area can expose the same path —
    returning the first would be a coin toss dressed up as an answer.
    """
    key = f"{method} {path}"
    return [(area, CAPABILITIES[area][key]) for area in AREAS if key in CAPABILITIES[area]]


def is_implemented(area: str, method: str, path: str) -> bool:
    """Is this capability callable today?"""
    return capability_status(area, method, path) == "implemented"
