/**
 * Capability statuses, generated.
 *
 * Generated by tools/sync-status.mjs from api-spec/status.json. Do not edit by hand —
 * run `node tools/sync-status.mjs` instead. CI fails if this drifts.
 *
 * Exposed so an application can render honest state without hard-coding a copy
 * that quietly goes stale — the failure this whole file exists to prevent.
 */

import type { CapabilityStatus } from "./types.ts";

/** When the matrix was last verified against the live network. */
export const VERIFIED_AT = "2026-08-14";

/**
 * Every capability, nested by area.
 *
 * Nested rather than flat because `GET /health` exists on both the registry and
 * the demo node. They are different endpoints on different hosts, and flattening
 * them into one key silently lost one of the two.
 */
export const CAPABILITIES: Readonly<Record<string, Readonly<Record<string, CapabilityStatus>>>> =
  Object.freeze({
    "discovery": Object.freeze({
      "GET /health": "implemented",
      "GET /nodes": "implemented",
      "GET /peers": "implemented",
      "GET /api/v1/peers": "not_yet_wired",
      "POST /api/v1/register": "implemented",
      "POST /api/v1/heartbeat": "implemented",
      "GET /nodes?callable=1": "implemented",
    }),
    "binding": Object.freeze({
      "POST /v1/bindings/initiate": "implemented",
      "POST /v1/bindings/resolve": "implemented",
      "POST /v1/bindings/authorize": "implemented",
      "GET /v1/bindings/{binding_session_id}/status": "implemented",
      "POST /v1/bindings/{binding_session_id}/cancel": "implemented",
      "POST /v1/node/bindings/pending": "implemented",
      "POST /v1/node/bindings/{binding_session_id}/accept": "implemented",
      "POST /v1/node/bindings/{binding_session_id}/reject": "implemented",
    }),
    "identity": Object.freeze({
      "POST /v1/auth/challenge": "implemented",
      "POST /v1/auth/device-login": "implemented",
      "GET /v1/operator/me/nodes": "implemented",
    }),
    "coordination": Object.freeze({
      "GET /healthz": "implemented",
      "GET /version": "implemented",
      "GET /openapi.json": "implemented",
      "GET /v1/capabilities": "implemented",
      "POST /v1/intents": "implemented",
      "GET /v1/sessions/{session_id}": "implemented",
      "GET /v1/sessions/{session_id}/proposal": "implemented",
      "POST /v1/sessions/{session_id}/commitment": "implemented",
      "GET /v1/sessions/{session_id}/commitment": "implemented",
      "POST /v1/sessions/{session_id}/authorize": "implemented",
      "POST /v1/sessions/{session_id}/cancel": "implemented",
      "GET /v1/sessions/{session_id}/result": "implemented",
      "GET /v1/sessions/{session_id}/receipt": "implemented",
      "GET /v1/sessions/{session_id}/events": "implemented",
      "POST /v1/objects": "implemented",
      "GET /v1/objects/{object_id}": "implemented",
      "POST /v1/runtimes": "implemented",
    }),
    "compute": Object.freeze({
      "GET /": "implemented",
      "GET /healthz": "implemented",
      "GET /readyz": "implemented",
      "GET /version": "implemented",
      "GET /openapi.json": "implemented",
      "GET /metrics": "implemented",
      "GET /v1/task-package": "implemented",
      "POST /v1/derive-core-intent": "implemented",
      "POST /v1/intents": "implemented",
      "GET /v1/sessions/{session_id}": "implemented",
      "GET /v1/sessions/{session_id}/proposal": "implemented",
      "POST /v1/sessions/{session_id}/commitment": "implemented",
      "POST /v1/sessions/{session_id}/authorize": "implemented",
      "POST /v1/sessions/{session_id}/cancel": "implemented",
      "GET /v1/sessions/{session_id}/result": "implemented",
      "GET /v1/sessions/{session_id}/receipt": "implemented",
      "GET /v1/sessions/{session_id}/events": "implemented",
      "POST /v1/objects": "implemented",
      "POST /v1/runtimes": "implemented",
    }),
    "economics": Object.freeze({
      "GET /v1/operator/me/credits": "not_yet_wired",
      "GET /v1/operator/me/evidence": "not_yet_wired",
    }),
    "oracle": Object.freeze({
      "CONTRACT EvidenceOracle.submitEvidence": "testing",
      "CONTRACT PythPriceAdapter.getPrice": "testing",
      "GET /v1/oracle/price": "planned",
      "POST /v1/oracle/report": "planned",
    }),
    "wallet": Object.freeze({
      "POST /v1/wallet/create": "planned",
      "POST /v1/wallet/session-key": "planned",
      "POST /v1/wallet/transfer": "planned",
    }),
    "dex": Object.freeze({
      "POST /v1/dex/intent": "planned",
      "GET /v1/dex/quote": "planned",
      "POST /v1/dex/solve": "planned",
      "GET /v1/dex/pools": "planned",
    }),
    "demo": Object.freeze({
      "GET /health": "implemented",
      "GET /identity": "implemented",
      "POST /echo": "implemented",
      "GET /verify-instructions": "implemented",
    }),
    "community": Object.freeze({
      "LINK https://discord.gg/libertynet": "planned",
      "LINK https://github.com/LibertyNetHQ": "implemented",
    }),
  });

/** Base URL per area. `null` where the area is not an HTTP surface. */
export const AREA_BASE_URLS: Readonly<Record<string, string | null>> = Object.freeze({
  "discovery": "https://registry.libertynet.ai",
  "binding": "https://registry.libertynet.ai",
  "identity": "https://registry.libertynet.ai",
  "coordination": "https://libertynet.ai/coordination",
  "compute": "https://libertynet.ai/compute",
  "economics": "https://registry.libertynet.ai",
  "oracle": null,
  "wallet": null,
  "dex": null,
  "demo": "https://libertynet.ai/demo-node",
  "community": null,
});

/** Areas, in the order the matrix lists them. */
export const AREAS = Object.freeze([
  "discovery",
  "binding",
  "identity",
  "coordination",
  "compute",
  "economics",
  "oracle",
  "wallet",
  "dex",
  "demo",
  "community",
] as const);

/** Status of one capability within an area. */
export function capabilityStatus(
  area: string,
  method: string,
  path: string,
): CapabilityStatus | undefined {
  return CAPABILITIES[area]?.[`${method} ${path}`];
}

/**
 * Find a capability without knowing its area.
 *
 * Returns every match, because more than one area can expose the same path —
 * returning the first would be a coin toss dressed up as an answer.
 */
export function findCapability(
  method: string,
  path: string,
): { area: string; status: CapabilityStatus }[] {
  const key = `${method} ${path}`;
  return AREAS.flatMap((area) => {
    const status = CAPABILITIES[area]?.[key];
    return status ? [{ area, status }] : [];
  });
}

/** Is this capability callable today? */
export function isImplemented(area: string, method: string, path: string): boolean {
  return capabilityStatus(area, method, path) === "implemented";
}
