#!/usr/bin/env node
/**
 * Regenerate everything derived from the capability matrix.
 *
 *     node tools/sync-status.mjs           write the generated files
 *     node tools/sync-status.mjs --check   fail if they are out of date
 *
 * `api-spec/status.json` is described everywhere as the single source of truth
 * for what exists. Until this file, that was a convention people had to remember:
 * the OpenAPI extensions and the SDK constants were maintained by hand and merely
 * *agreed* with the matrix. A convention that nothing enforces is a convention
 * that drifts on a busy Friday.
 *
 * Now the matrix is genuinely authoritative. Change a status there, run this, and
 * the OpenAPI spec, both SDKs and the docs table all change with it. `--check`
 * runs in CI and fails if anyone edits a generated file by hand — the same
 * discipline as `gofmt -l`.
 *
 * Deliberately NOT generated: prose. A capability moving from `planned` to
 * `implemented` needs a human to write what it does; a machine that invented that
 * paragraph would be manufacturing exactly the confidence this project exists to
 * avoid.
 */

import { readFile, writeFile } from "node:fs/promises";
import path from "node:path";

const HERE = path.dirname(new URL(import.meta.url).pathname);
const ROOT = path.resolve(HERE, "..");
const checkOnly = process.argv.includes("--check");

const status = JSON.parse(await readFile(path.join(ROOT, "api-spec/status.json"), "utf8"));

const BANNER = (source) =>
  `Generated by tools/sync-status.mjs from ${source}. Do not edit by hand —\n` +
  `run \`node tools/sync-status.mjs\` instead. CI fails if this drifts.`;

const outputs = [];

// ---------------------------------------------------------------------------
// 1. OpenAPI x-ln-status
// ---------------------------------------------------------------------------

/**
 * Patch `x-ln-status` values in place.
 *
 * A line rewrite rather than a YAML round-trip: re-emitting the whole document
 * would reflow every hand-written description and turn a one-line status change
 * into a thousand-line diff nobody reviews.
 */
async function openapi() {
  const file = path.join(ROOT, "api-spec/libertynet-v1.yaml");
  const src = await readFile(file, "utf8");

  const matrix = new Map();
  for (const group of status.groups) {
    for (const e of group.endpoints) {
      if (e.method === "CONTRACT" || e.method === "LINK") continue;
      matrix.set(`${e.method} ${e.path}`, e.status);
    }
  }

  const lines = src.split("\n");
  let currentPath = null;
  let currentMethod = null;
  let changed = 0;

  for (let i = 0; i < lines.length; i++) {
    const p = /^  (\/\S*):\s*$/.exec(lines[i]);
    if (p) {
      currentPath = p[1];
      currentMethod = null;
      continue;
    }
    const m = /^    (get|post|put|delete|patch):\s*$/.exec(lines[i]);
    if (m) {
      currentMethod = m[1].toUpperCase();
      continue;
    }
    const s = /^(      x-ln-status:\s*)(\S+)\s*$/.exec(lines[i]);
    if (s && currentPath && currentMethod) {
      const want = matrix.get(`${currentMethod} ${currentPath}`);
      if (want && want !== s[2]) {
        lines[i] = `${s[1]}${want}`;
        changed++;
      }
    }
  }

  outputs.push({ file, content: lines.join("\n"), changed });
}

// ---------------------------------------------------------------------------
// 2. TypeScript SDK constants
// ---------------------------------------------------------------------------

async function typescript() {
  const byArea = status.groups.map((g) => ({
    id: g.id,
    base: g.base_url,
    endpoints: g.endpoints.map((e) => ({ key: `${e.method} ${e.path}`, status: e.status })),
  }));

  const content = `/**
 * Capability statuses, generated.
 *
 * ${BANNER("api-spec/status.json").split("\n").join("\n * ")}
 *
 * Exposed so an application can render honest state without hard-coding a copy
 * that quietly goes stale — the failure this whole file exists to prevent.
 */

import type { CapabilityStatus } from "./types.ts";

/** When the matrix was last verified against the live network. */
export const VERIFIED_AT = ${JSON.stringify(status.verified_at)};

/**
 * Every capability, nested by area.
 *
 * Nested rather than flat because \`GET /health\` exists on both the registry and
 * the demo node. They are different endpoints on different hosts, and flattening
 * them into one key silently lost one of the two.
 */
export const CAPABILITIES: Readonly<Record<string, Readonly<Record<string, CapabilityStatus>>>> =
  Object.freeze({
${byArea.map((a) => `    ${JSON.stringify(a.id)}: Object.freeze({\n${a.endpoints.map((e) => `      ${JSON.stringify(e.key)}: ${JSON.stringify(e.status)},`).join("\n")}\n    }),`).join("\n")}
  });

/** Base URL per area. \`null\` where the area is not an HTTP surface. */
export const AREA_BASE_URLS: Readonly<Record<string, string | null>> = Object.freeze({
${byArea.map((a) => `  ${JSON.stringify(a.id)}: ${JSON.stringify(a.base ?? null)},`).join("\n")}
});

/** Areas, in the order the matrix lists them. */
export const AREAS = Object.freeze([
${byArea.map((a) => `  ${JSON.stringify(a.id)},`).join("\n")}
] as const);

/** Status of one capability within an area. */
export function capabilityStatus(
  area: string,
  method: string,
  path: string,
): CapabilityStatus | undefined {
  return CAPABILITIES[area]?.[\`\${method} \${path}\`];
}

/**
 * Find a capability without knowing its area.
 *
 * Returns every match, because more than one area can expose the same path —
 * returning the first would be a coin toss dressed up as an answer.
 */
export function findCapability(
  method: string,
  path: string,
): { area: string; status: CapabilityStatus }[] {
  const key = \`\${method} \${path}\`;
  return AREAS.flatMap((area) => {
    const status = CAPABILITIES[area]?.[key];
    return status ? [{ area, status }] : [];
  });
}

/** Is this capability callable today? */
export function isImplemented(area: string, method: string, path: string): boolean {
  return capabilityStatus(area, method, path) === "implemented";
}
`;

  outputs.push({ file: path.join(ROOT, "sdk/typescript/src/capabilities.ts"), content });
}

// ---------------------------------------------------------------------------
// 3. Python SDK constants
// ---------------------------------------------------------------------------

async function python() {
  const byArea = status.groups.map((g) => ({
    id: g.id,
    base: g.base_url,
    endpoints: g.endpoints.map((e) => [`${e.method} ${e.path}`, e.status]),
  }));

  const content = `"""Capability statuses, generated.

${BANNER("api-spec/status.json")}

Exposed so an application can render honest state without hard-coding a copy that
quietly goes stale — the failure this whole file exists to prevent.
"""

from __future__ import annotations

from types import MappingProxyType

__all__ = [\n    "VERIFIED_AT",\n    "CAPABILITIES",\n    "AREA_BASE_URLS",\n    "AREAS",\n    "capability_status",\n    "find_capability",\n    "is_implemented",\n]

#: When the matrix was last verified against the live network.
VERIFIED_AT = ${JSON.stringify(status.verified_at)}

#: Every capability, nested by area.
#:
#: Nested rather than flat because \`\`GET /health\`\` exists on both the registry
#: and the demo node. They are different endpoints on different hosts, and
#: flattening them into one key silently lost one of the two.
CAPABILITIES = MappingProxyType({
${byArea.map((a) => `    ${JSON.stringify(a.id)}: MappingProxyType({\n${a.endpoints.map(([k, v]) => `        ${JSON.stringify(k)}: ${JSON.stringify(v)},`).join("\n")}\n    }),`).join("\n")}
})

#: Base URL per area. \`\`None\`\` where the area is not an HTTP surface.
AREA_BASE_URLS = MappingProxyType({
${byArea.map((a) => `    ${JSON.stringify(a.id)}: ${a.base ? JSON.stringify(a.base) : "None"},`).join("\n")}
})

#: Areas, in the order the matrix lists them.
AREAS = (${byArea.map((a) => JSON.stringify(a.id)).join(", ")})


def capability_status(area: str, method: str, path: str) -> str | None:
    """Status of one capability within an area, or \`\`None\`\` if not listed."""
    return CAPABILITIES.get(area, {}).get(f"{method} {path}")


def find_capability(method: str, path: str) -> list[tuple[str, str]]:
    """Find a capability without knowing its area.

    Returns every match, because more than one area can expose the same path —
    returning the first would be a coin toss dressed up as an answer.
    """
    key = f"{method} {path}"
    return [(area, CAPABILITIES[area][key]) for area in AREAS if key in CAPABILITIES[area]]


def is_implemented(area: str, method: str, path: str) -> bool:
    """Is this capability callable today?"""
    return capability_status(area, method, path) == "implemented"
`;

  outputs.push({ file: path.join(ROOT, "sdk/python/libertynet/capabilities.py"), content });
}

// ---------------------------------------------------------------------------
// 4. The docs status table
// ---------------------------------------------------------------------------

async function docsTable() {
  const rows = [];
  for (const group of status.groups) {
    rows.push(`\n### ${group.title}\n`);
    if (group.note) rows.push(`${group.note}\n`);
    rows.push("| Endpoint | Status | Notes |");
    rows.push("|---|---|---|");
    for (const e of group.endpoints) {
      const path = e.method === "LINK" ? e.path : `\`${e.method} ${e.path}\``;
      rows.push(`| ${path} | <Status level="${e.status}" /> | ${(e.note ?? "").replace(/\|/g, "\\|")} |`);
    }
  }

  const content = `{/* ${BANNER("api-spec/status.json").replace(/\n/g, " ")} */}

import { Status } from '/snippets/status.mdx';

{/* Verified against the live network on ${status.verified_at}. */}
${rows.join("\n")}
`;

  outputs.push({ file: path.join(ROOT, "docs-site/snippets/capability-table.mdx"), content });
}

// ---------------------------------------------------------------------------

// ---------------------------------------------------------------------------
// 5. the matrix vendored into the scaffolder
// ---------------------------------------------------------------------------

/**
 * `--describe` reads a sentence against the capability matrix, and has to do it
 * with no network — so the package carries its own copy. A copy is a drift risk
 * by construction, which is why it is generated here and checked in CI: a
 * scaffolder telling people credits work because it is holding last month's
 * matrix is the exact failure this file exists to prevent.
 */
async function scaffolderMatrix() {
  outputs.push({
    file: path.join(ROOT, "create-libertynet-agent/src/status.json"),
    content: await readFile(path.join(ROOT, "api-spec/status.json"), "utf8"),
  });
}

await openapi();
await typescript();
await python();
await docsTable();
await scaffolderMatrix();

let stale = 0;

for (const out of outputs) {
  const existing = await readFile(out.file, "utf8").catch(() => null);
  const same = existing === out.content;

  if (checkOnly) {
    if (!same) {
      stale++;
      console.error(`  ✗ ${path.relative(ROOT, out.file)} is out of date`);
    }
  } else if (!same) {
    await writeFile(out.file, out.content);
    console.log(`  updated ${path.relative(ROOT, out.file)}`);
  }
}

const total = status.groups.reduce((n, g) => n + g.endpoints.length, 0);

if (checkOnly) {
  if (stale === 0) {
    console.log(`\n✓ generated files match the matrix (${total} capabilities, ${outputs.length} files)\n`);
    process.exit(0);
  }
  console.error(
    `\n✗ ${stale} generated file(s) are stale.\n\n` +
      `  Run:  node tools/sync-status.mjs\n\n` +
      `  If you edited one of those files by hand, edit api-spec/status.json instead —\n` +
      `  it is the source, and hand-edits get overwritten.\n`,
  );
  process.exit(1);
}

console.log(`\n✓ synced ${total} capabilities into ${outputs.length} generated file(s)\n`);
